# Generated by Django 5.1.5 on 2026-09-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("car_wash", "Car Wash"),
                            ("climatizacion", "Aire Acondicionado y Climatizacion"),
                            ("mecanica", "Taller Mecanico"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("precio_desde", models.DecimalField(decimal_places=0, max_digits=10)),
                ("duracion_minutos", models.PositiveIntegerField(default=60)),
                ("destacado", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "servicio",
                "verbose_name_plural": "servicios",
                "ordering": ["categoria", "nombre"],
            },
        ),
    ]
