# Generated by Django 5.1.5 on 2026-09-12 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "sku",
                    models.CharField(
                        help_text="Codigo interno unico del producto.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("repuesto", "Repuesto"),
                            ("lubricante", "Lubricante"),
                            ("neumatico", "Neumatico"),
                            ("accesorio", "Accesorio"),
                            ("insumo", "Insumo de limpieza"),
                        ],
                        default="repuesto",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "stock_minimo",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Umbral bajo el cual el producto se marca como stock critico.",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "ordering": ["nombre"],
            },
        ),
    ]
