# Generated by Django 5.1.5 on 2026-09-12 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_cliente", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=20)),
                ("marca_vehiculo", models.CharField(max_length=60)),
                ("modelo_vehiculo", models.CharField(max_length=60)),
                ("patente", models.CharField(max_length=10)),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                ("comentarios", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmada", "Confirmada"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=12,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="citas",
                        to="catalogo.servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "cita",
                "verbose_name_plural": "citas",
                "ordering": ["-fecha", "-hora"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("estado__in", ["pendiente", "confirmada"])),
                        fields=("fecha", "hora"),
                        name="unica_cita_por_bloque_horario",
                    )
                ],
            },
        ),
    ]
